import { Noto_Sans_KR } from 'next/font/google';
import '@/scss/reset.scss';
import ClientProviders from '@/components/ClientProvider';

const notoKR = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata = {
  title: 'PG 통합Link',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={notoKR.className}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
